services:
  # Backend API
  - type: web
    name: meeting-summarizer-api
    env: python
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "uvicorn backend.app:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 8000
    healthCheckPath: /health

  # Frontend
  - type: web
    name: meeting-summarizer-frontend
    env: static
    buildCommand: ""
    staticPublishPath: ./frontend/static
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
